#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8
yabai -m config external_bar main:0:60

# space 1: terminal and todo
yabai -m rule --add app="iTerm2" space=^1
yabai -m rule --add app="kitty" space=^1
yabai -m rule --add app="Things" space=^1

# space 2: development
yabai -m rule --add app="JetBrains Rider.*" space=^2
yabai -m rule --add app="PhpStorm.*" space=^2

# space 3: web
yabai -m rule --add app="Safari" space=^3

# space 4: private/utility apps
yabai -m space 4 --layout stack
yabai -m rule --add app="Superhuman" space=^4
yabai -m rule --add app="DataGrip" space=^4
yabai -m rule --add app="Pixelmator*" space=^4

# space 5: remoting
yabai -m space 5 --layout stack
yabai -m rule --add app="Jump Desktop" space=^5
yabai -m rule --add app="Parsec" space=^5

# display 2: off-stream and out of the way
yabai -m rule --add app="Discord" display=2
yabai -m rule --add app="Music" display=2
yabai -m rule --add app="OBS" display=2
yabai -m rule --add app="Audio Hijack" display=2
yabai -m rule --add app="Hyper*" display=2
yabai -m rule --add app="Podcasts" display=2

# things which create floating children
yabai -m rule --add title="JetBrains Toolbox" manage=off mouse_follows_focus=off
yabai -m rule --add app="iStat Menus" manage=off mouse_follows_focus=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off

