#!/bin/bash

read -p "enter optional tag suffix (leave empty for none): " suffix

git checkout -f master
git pull upstream master

i=0
while true; do
  tag=$(date +%Y.%-m%d.$i)
  [[ -n "$suffix" ]] && tag="$tag-$suffix"
  if git tag "$tag"; then
    break
  fi
  ((i++))
done

read -p "ready to push $tag (enter to proceed)"

git push upstream "$tag"

