#! /opt/homebrew/bin/fish

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Prepare for streaming
# @raycast.mode silent

# Documentation:
# @raycast.author ppy
# @raycast.authorURL https://raycast.com/ppy

echo "Purging command line history..."

yes all | history delete --contains "SHARED"
yes all | history delete --contains ".osu."
yes all | history delete --contains "ping"
yes all | history delete --contains "youtube."
yes all | history delete --contains "google."
yes all | history delete --contains "cheat"
yes all | history delete --contains "history delete"
yes all | history delete --contains "yt-dlp"

echo "Killing unnecessary apps..."

pkill -x "datagrip"
pkill -x "Superhuman"
pkill -x "Safari"
pkill -x "Transmit"
pkill -x "Bear"
pkill -x "Keychain Access"
pkill -x "IINA"

# echo "Destroying browser history..."

# rm -rf ~/Library/Caches/Safari
# rm -rf ~/Library/Safari/History*
# touch ~/Library/Caches/Safari

echo "Emptying trash..."

rm -rf ~/.Trash/*

echo "Starting streaming apps..."

open /Applications/Audio\ Hijack.app
open /Applications/OBS.app
open /Applications/Safari.app
# open /System/Applications/Music.app
# sleep 1

sleep 2

echo "Deleting clipboard history..."

skhd -k "cmd+shift-h"; skhd -k "ctrl+shift-x"; skhd -k "return"; sleep 1; skhd -k "escape"

echo "Deleting chat history..."

skhd -k "cmd+shift-space"; skhd -k "ctrl+shift-x"; skhd -k "return"; sleep 1; skhd -k "escape"

echo "Starting now playing updates..."

update-now-playing
