#!/bin/bash

# security add-generic-password -D secret -U -a $USER -s "$1" -w "$2"

for var in $(security dump-keychain ${KEYCHAIN} | grep 0x00000007 | awk -F= '{print $2}' | tr -d \" | grep "ENV_")
do
    outVar="${var:4}";
    export $outVar=$(security find-generic-password -w -a ${USER} -s "$var");
done

if [ $SHLVL -le 2 ] ; then
    export DB_HOST="127.0.0.1"
    export DB_PORT="3309"

    tmux rename-window "**secrets**"

    fish
fi
