#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Format standup output from things output
# @raycast.mode compact
# @raycast.icon 🧍

# Documentation:
# @raycast.author ppy
# @raycast.authorURL https://raycast.com/ppy
# @raycast.packageName Safari GitHub actions

# Read the input from the clipboard
input=$(pbpaste)

# Initialize the previous date variable
prev_date=""

# Initialize the output variable
output=""
first=1

# Process each line of the input
while IFS= read -r line; do
  # Extract the date from the current line
  current_date=$(echo "$line" | sed -n 's/.*(\([0-9/]*\)).*/\1/p' | sed 's/\//-/g')

  # If the current date is different from the previous date, update the output with the new date header
  if [ "$current_date" != "$prev_date" ]; then
    if [ $first -eq 1 ]; then
        output+="\`\`\`md\n# $current_date\n\n"
        first=0
    else
        output+="\`\`\`\n\`\`\`md\n# $current_date\n\n"
    fi

    prev_date="$current_date"
  fi
  
  # Extract the status of the task
  status=$(echo "$line" | grep -o '\[[x~ ]\]')
  
  # Extract the description of the task, removing the date
  description=$(echo "$line" | sed -E 's/^.*\) //')
  
  # Append the formatted line to the output
  output+="- $status $description\n"
done <<< "$input"

# Copy the output to the clipboard
echo -e "$output" | pbcopy

