#!/bin/bash

url=`safari-ctl`
repo=`echo $url | sed -e 's,https://github.com/[^/]*/\([^/]*\).*,\1,g'`

cd ~/Projects/$repo/

choice=`printf "checkout\napprove\napprove & automerge\napprove & force merge\nforce merge\n \n# operating on\n# repo: $repo\n# URL: $url" | choose -i`

case "$choice" in
    0)
        # checkout PR
        /usr/local/bin/gh pr checkout $url
        ;;
    1)
        # just approve
        /usr/local/bin/gh pr review $url -a
        ;;
    2)
        # approve with automerge
        /usr/local/bin/gh pr review $url -a
        /usr/local/bin/gh pr merge $url --auto -m
        ;;
    3)
        # approve with forced merge
        /usr/local/bin/gh pr review $url -a
        /usr/local/bin/gh pr merge $url --merge --disable-auto
        /usr/local/bin/gh pr merge $url --merge --admin
        ;;
    4)
        # force merge
        /usr/local/bin/gh pr merge $url --merge --disable-auto
        /usr/local/bin/gh pr merge $url --merge --admin
        ;;
    8)
        eval "$(gh pr view $url --json "title,url" | jq -r '@sh "title=\(.title)", @sh "url=\(.url)"')"
        echo "- [ ] $title ($url)" | pbcopy
esac
