#! /bin/bash

version=$(cd ../osu-framework; gh release list -L1 | head -n1 | awk '{print $1;}')

git btm
git checkout -B update-framework

sed -i '' -e "s/ppy.osu.Framework\" Version=\"[^\"]*\"/ppy.osu.Framework\" Version=\"${version}\"/g" osu.Game/osu.Game.csproj
sed -i '' -e "s/ppy.osu.Framework\" Version=\"[^\"]*\"/ppy.osu.Framework\" Version=\"${version}\"/g" osu.iOS.props
sed -i '' -e "s/ppy.osu.Framework.iOS\" Version=\"[^\"]*\"/ppy.osu.Framework.iOS\" Version=\"${version}\"/g" osu.iOS.props
sed -i '' -e "s/ppy.osu.Framework.Android\" Version=\"[^\"]*\"/ppy.osu.Framework.Android\" Version=\"${version}\"/g" osu.Android.props

git commit -a -m "Update framework"
git push --force --set-upstream origin update-framework

hub pull-request
